### ISSUE TITLE
Compiling Error ubuntu 16.04 

### ISSUE THREAD

**Issue by rouzinho** [cedar/cedar#8]
Hi Guys,

I need to compile Cedar for ubuntu 16.04 (my other version on 18.04 works great).
I got this error :
`/home/altair/codes/cedar/tests/unit/devices/ComponentChannelSharing/component_channel_sharing.cpp: In destructor ‘virtual TestChannel::~TestChannel()’:
/home/altair/codes/cedar/tests/unit/devices/ComponentChannelSharing/component_channel_sharing.cpp:60:46: error: ‘prepareChannelDestructAbsolutelyRequired’ was not declared in this scope
     prepareChannelDestructAbsolutelyRequired();`

Since I begin to master Cedar quite well, I checked and it seems the destructor prepareChannelDestructAbsolutelyRequired() in cedar::dev::Channel is not implemented yet.

Best regards,

Quentin

**Comment by tekuejpp** [comment]
Hi Quentin,

sorry for the late response.
You are right the function prepareChannelDestructAbsolutelyRequired() is not implemented and it probably should not exist and somebody mistook it for the function prepareComponentDestructAbsolutelyRequired of the Component class, which wraps the channels.

Sorry this issue went unnoticed so long. We usually compile cedar without the unit tests (make cedar instead of make) and thus did not stumble across this error.
We will omit this bad practice before the next commit ;-)

Best regards,

Jan
